# Font configuration
font_family        Hack Nerd Font
font_size 17.0
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 Symbols Nerd Font Mono

# Window opacity
background_opacity 0.7

# Base colors
background #131229
foreground #c8c2d6

# Cursor colors
cursor            #439fb5
cursor_text_color #131229

# Selection colors
selection_background #3a3356
selection_foreground none

# URL styling
url_color #5db0c2
url_style straight

# Window borders & bell
active_border_color   #1184a3
inactive_border_color #4d426d
bell_border_color     #c24b57
visual_bell_color     #c24b57
scrollbar_handle_color #923852

# Tab bar
tab_bar_style           powerline
tab_powerline_style     angled
tab_bar_background      #131229
active_tab_foreground   #131229
active_tab_background   #1184a3
active_tab_font_style   bold
inactive_tab_foreground #988fae
inactive_tab_background #1f1e38
inactive_tab_font_style normal

#: 16 terminal colors

#: black
color0 #2e294e
color8 #6d6288

#: red
color1 #c24b57
color9 #e26d7d

#: green
color2  #b8586f
color10 #d496a5

#: yellow
color3  #a88554
color11 #ead97c

#: blue
color4  #1184a3
color12 #3ab1c6

#: magenta
color5  #826c9f
color13 #c487ae

#: cyan
color6  #439fb5
color14 #7de8f4

#: white
color7  #c8c2d6
color15 #ffffff
