font_family        Hack Nerd Font
font_size 17.0
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 Symbols Nerd Font Mono

scrollbar_handle_color #923852

url_color #0087bd
url_style straight

visual_bell_color #923852

tab_bar_style powerline
tab_powerline_style angled

active_tab_foreground   #131229
active_tab_background   #1184a3
active_tab_font_style   bold
inactive_tab_foreground #1184a3
inactive_tab_background #131229
inactive_tab_font_style normal

background #131229
foreground #cccccc
selection_background #2e294e
selection_foreground #923852

background_opacity 0.7

#: black

 color0 #5a4a85
 color8 #7676a6

#: red

 color1 #2e294e
 color9 #5a4a85

#: green

 color2  #923852
 color10 #b36b7a

#: yellow

 color3  #A0546D
 color11 #c487ae

#: blue

 color4  #d3a593
 color12 #edcaba

#: magenta

 color5  #1184a3
 color13 #3ab1c6

#: cyan

 color6  #439fb5
 color14 #6dc3db

#: white

 color7  #ffffff
 color15 #ffffff
