# i put this here cause i was getting a lot of conflicts moving stuff between my pc and laptop
# i will change this when i set up swww

$wallp_1 = swww img ~/.config/wallpapers/teto_miku_wallpaper_1.webp --transition-fps 255 --transition-step 5
$wallp_2 = swww img ~/.config/wallpapers/teto_miku_wallpaper_2.png --transition-fps 255 --transition-step 5
$wallp_3 = swww img ~/.config/wallpapers/teto_miku_wallpaper_3.webp --transition-fps 255 --transition-step 5
$wallp_4 = swww img ~/.config/wallpapers/teto_miku_wallpaper_4.png --transition-fps 255 --transition-step 5
$wallp_5 = swww img ~/.config/wallpapers/teto_miku_wallpaper_5.jpg --transition-fps 255 --transition-step 5
$wallp_6 = swww img ~/.config/wallpapers/teto_miku_wallpaper_6.jpg --transition-fps 255 --transition-step 5
